name: CONTEXT Golden Suite

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  goldens:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Run CONTEXT golden tests
        run: python tests/run_goldens.py
